/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int F_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void F_fun_incref(void);
void F_fun_decref(void);
casadi_int F_fun_n_out(void);
casadi_int F_fun_n_in(void);
const char* F_fun_name_in(casadi_int i);
const char* F_fun_name_out(casadi_int i);
const casadi_int* F_fun_sparsity_in(casadi_int i);
const casadi_int* F_fun_sparsity_out(casadi_int i);
int F_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
