/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) F_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[20] = {5, 5, 0, 3, 3, 6, 9, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* F:(i0[3],i1,i2[2],i3[2])->(o0[5x5,12nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][2] : 0;
  a1=cos(a0);
  a2=arg[0] ? arg[0][0] : 0;
  a3=tan(a2);
  a4=arg[2] ? arg[2][0] : 0;
  a5=2.8000000000000001e-02;
  a6=arg[1] ? arg[1][0] : 0;
  a7=casadi_sq(a6);
  a5=(a5*a7);
  a4=(a4-a5);
  a3=(a3/a4);
  a1=(a1-a3);
  a5=2.5000000000000001e-03;
  a7=arg[2] ? arg[2][1] : 0;
  a8=(a7*a4);
  a9=sin(a2);
  a9=(a8*a9);
  a10=(a5*a9);
  a10=(a1*a10);
  a11=cos(a2);
  a8=(a8*a11);
  a12=400.;
  a13=(a8/a12);
  a14=(1./a4);
  a15=cos(a2);
  a15=casadi_sq(a15);
  a14=(a14/a15);
  a14=(a13*a14);
  a10=(a10+a14);
  a10=(-a10);
  if (res[0]!=0) res[0][0]=a10;
  a10=sin(a0);
  a14=sin(a2);
  a14=(a12*a14);
  a15=(a9/a14);
  a8=(a8/a14);
  a16=(a8/a14);
  a17=cos(a2);
  a12=(a12*a17);
  a16=(a16*a12);
  a15=(a15+a16);
  a15=(a10*a15);
  if (res[0]!=0) res[0][1]=a15;
  a16=cos(a2);
  a15=(a16*a15);
  a12=(a8*a10);
  a2=sin(a2);
  a12=(a12*a2);
  a15=(a15+a12);
  a9=(a5*a9);
  a9=(a6*a9);
  a15=(a15-a9);
  if (res[0]!=0) res[0][2]=a15;
  a15=sin(a0);
  a15=(a13*a15);
  a15=(-a15);
  if (res[0]!=0) res[0][3]=a15;
  a0=cos(a0);
  a8=(a8*a0);
  a0=(-a8);
  if (res[0]!=0) res[0][4]=a0;
  a8=(a16*a8);
  a8=(-a8);
  if (res[0]!=0) res[0][5]=a8;
  a7=(a11*a7);
  a8=(a5*a7);
  a8=(a1*a8);
  a3=(a3/a4);
  a13=(a13*a3);
  a8=(a8+a13);
  if (res[0]!=0) res[0][6]=a8;
  a8=(a7/a14);
  a8=(a10*a8);
  a13=(-a8);
  if (res[0]!=0) res[0][7]=a13;
  a7=(a5*a7);
  a7=(a6*a7);
  a8=(a16*a8);
  a7=(a7-a8);
  if (res[0]!=0) res[0][8]=a7;
  a11=(a11*a4);
  a4=(a5*a11);
  a1=(a1*a4);
  if (res[0]!=0) res[0][9]=a1;
  a14=(a11/a14);
  a10=(a10*a14);
  a14=(-a10);
  if (res[0]!=0) res[0][10]=a14;
  a5=(a5*a11);
  a6=(a6*a5);
  a16=(a16*a10);
  a6=(a6-a16);
  if (res[0]!=0) res[0][11]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void F_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int F_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* F_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
