/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int x_pred(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void x_pred_incref(void);
void x_pred_decref(void);
casadi_int x_pred_n_out(void);
casadi_int x_pred_n_in(void);
const char* x_pred_name_in(casadi_int i);
const char* x_pred_name_out(casadi_int i);
const casadi_int* x_pred_sparsity_in(casadi_int i);
const casadi_int* x_pred_sparsity_out(casadi_int i);
int x_pred_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
